/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemacontable;


import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;


import Controladores.ControladorTablaLibroDiario;
import ModeloContable.Cuenta;
import ModeloContable.Registro;
import ModeloContable.Tipo;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JRadioButton;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author pc
 */
public class RegistroAsiento extends javax.swing.JFrame {
    private ControladorTablaLibroDiario controladorTablaLibroDiario;
    private ControladorTablaRegistro controladorTablaRegistro;
    private List<Registro> nuevosRegistros;
    private List<Cuenta> cuentasDisp;
    private Cuenta cuentaSeleccionada;
    
    //variables auxiliares 
    private double totalDebe;
    private double totalHaber;
    
    //Debo usar este tipo aqui ya que no es posible saber si un rdio button ha sido seleccionado
    // al hacer click a cualquier radio button asi se cambiara 
    private Tipo tipoTransaccion;
    
    class VerificadorValorRegistro extends InputVerifier{

        @Override
        public boolean verify(JComponent input) {
            try{
                Double.valueOf(txtValor.getText());
            }catch(NumberFormatException e){
                System.out.println("Error convirtiendo el valor");
                JOptionPane.showMessageDialog(rootPane,"Introduzca un valor valido para el monto de la transacción.","Error en el valor.",JOptionPane.ERROR_MESSAGE);
                return false;
            }
            
            return true;
           
        }
        
    }
    /**
     * Creates new form RegistroAsiento
     */
    public RegistroAsiento(ControladorTablaLibroDiario controladorTablaLibroDiario,List<Cuenta> cuentasDisp) {
        this.setVisible(rootPaneCheckingEnabled);
        initComponents();
        controladorTablaRegistro = new ControladorTablaRegistro();
       
        this.nuevosRegistros = new ArrayList<>();
        this.controladorTablaLibroDiario = controladorTablaLibroDiario;
        this.cuentasDisp = cuentasDisp;
        
        
        btngTipoTransaccion.add(rbtnAbono);
        btngTipoTransaccion.add(rbtnCargo);
        txtValor.setInputVerifier( new VerificadorValorRegistro());
        
        configurarTablaRegistro();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTipoTransaccion = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRegistrosNuevos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbtnCargo = new javax.swing.JRadioButton();
        rbtnAbono = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnAñadirTransaccion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnGuardarNuevasTransacciones = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCuentaSeleccionada = new javax.swing.JTextField();
        btnGuardarTransaccionModificada = new javax.swing.JButton();
        btnEliminarSeleccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tablaRegistrosNuevos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Cuenta", "Descripción", "Debe", "Haber"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaRegistrosNuevos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tablaRegistrosNuevos);

        jLabel5.setText("Cuenta:");

        jLabel6.setText("Valor:");

        jLabel7.setText("Tipo de movimiento:");

        rbtnCargo.setText("Cargo");
        rbtnCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnCargoMouseClicked(evt);
            }
        });

        rbtnAbono.setText("Abono");
        rbtnAbono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnAbonoMouseClicked(evt);
            }
        });

        jLabel1.setText("Incluye IVA:");

        jCheckBox1.setText("IVA");

        jLabel2.setText("Descripción de la transacción:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        btnAñadirTransaccion.setText("Añadir transacción.");
        btnAñadirTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirTransaccionActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar transacción seleccionada.");

        btnGuardarNuevasTransacciones.setText("Guardar.");
        btnGuardarNuevasTransacciones.setEnabled(false);
        btnGuardarNuevasTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNuevasTransaccionesActionPerformed(evt);
            }
        });

        jButton4.setText("Q");
        jButton4.setToolTipText("Click para buscar una cuenta");

        jLabel3.setText("Fecha:");

        btnGuardarTransaccionModificada.setText("Guardar modificación.");
        btnGuardarTransaccionModificada.setEnabled(false);

        btnEliminarSeleccion.setText("Eliminar selección.");
        btnEliminarSeleccion.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtCuentaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4)))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 89, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAñadirTransaccion)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(28, 28, 28)
                        .addComponent(btnGuardarTransaccionModificada)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarNuevasTransacciones)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarSeleccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jButton4)
                            .addComponent(jLabel3)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCuentaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnCargo)
                            .addComponent(rbtnAbono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jCheckBox1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadirTransaccion)
                    .addComponent(jButton2)
                    .addComponent(btnGuardarNuevasTransacciones)
                    .addComponent(btnGuardarTransaccionModificada)
                    .addComponent(btnEliminarSeleccion))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void btnAñadirTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirTransaccionActionPerformed
        Registro registroNuevo = new Registro();
        
       
        
        boolean camposVacios = txtValor.getText().isBlank()
                & txtCuentaSeleccionada.getText().isBlank()
                & txtFecha.getText().isBlank()
                & (tipoTransaccion==null);
        
        if (camposVacios){
            JOptionPane.showInternalMessageDialog(rootPane,"Ingrese todos los datos necesarios","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        registroNuevo.setCuenta(null);
        registroNuevo.setTipo(tipoTransaccion);
        registroNuevo.setValor(Double.parseDouble(txtValor.getText()));
        registroNuevo.setFechaRegistro(LocalDate.parse(txtFecha.getText()));
        registroNuevo.getDescripcion().append(txtDescripcion.getText());
        nuevosRegistros.add(registroNuevo);
        
        
    }//GEN-LAST:event_btnAñadirTransaccionActionPerformed

    private void rbtnCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnCargoMouseClicked
        tipoTransaccion = Tipo.DEBE;
      
    }//GEN-LAST:event_rbtnCargoMouseClicked

    private void rbtnAbonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnAbonoMouseClicked
       tipoTransaccion = Tipo.HABER;
        
    }//GEN-LAST:event_rbtnAbonoMouseClicked

    private void btnGuardarNuevasTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNuevasTransaccionesActionPerformed
       controladorTablaLibroDiario.añadirRegistros(nuevosRegistros);
        
        
    }//GEN-LAST:event_btnGuardarNuevasTransaccionesActionPerformed

    /**
     * @param args the command line arguments
     */

    /***
     * Limpia todos los parametros a rellenar en la interfaz para crear una transaccion
     */
    public void limpiarParametros(){
        btngTipoTransaccion.clearSelection();
        txtDescripcion.setText(null);
        txtFecha.setText(null);
        txtValor.setText(null);
        txtCuentaSeleccionada.setText(null);
    }
    
    public final void configurarTablaRegistro(){
        tablaRegistrosNuevos.setModel(controladorTablaRegistro);
        tablaRegistrosNuevos.setDragEnabled(false);
        
        int numCols = tablaRegistrosNuevos.getColumnCount();
        
        for(int i=0;i<numCols;i++){
            if(i==0){
                tablaRegistrosNuevos.getColumnModel().getColumn(i).setHeaderValue("Fecha");
            }
            if(i==1){
                tablaRegistrosNuevos.getColumnModel().getColumn(i).setHeaderValue("Cuenta");
            }
            if(i==2){
                tablaRegistrosNuevos.getColumnModel().getColumn(i).setHeaderValue("Descripción");
            }
            if(i==3){
                tablaRegistrosNuevos.getColumnModel().getColumn(i).setHeaderValue("Debe");
            }
            if(i==4){
                tablaRegistrosNuevos.getColumnModel().getColumn(i).setHeaderValue("Haber");
            }
            
        }
        
        
    }
    
    
    class ControladorTablaRegistro extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return (nuevosRegistros!=null)?nuevosRegistros.size():0;
        }

        @Override
        public int getColumnCount() {
            return 5;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Registro registro = nuevosRegistros.get(rowIndex);
            
            double debe = (registro.getTipo().equals(Tipo.DEBE))?registro.getValor():0;
            double haber = (registro.getTipo().equals(Tipo.HABER))?registro.getValor():0;
            
            totalDebe += debe;
            totalHaber += haber;
            
            
            if(rowIndex == getRowCount()+1 && columnIndex == 0){
                return "Total";
            }
            
            switch(columnIndex){
                case 0:
                    return registro.getFechaRegistroFormateada();
                case 1:
                    return registro.getCuenta().getNombre();
                case 2:
                    return registro.getDescripcion().toString();
                case 3:
                    return (debe==0)?"":debe;
                case 4:
                    return (haber==0)?"":haber;
                default:
                    return null;
                
            }
            
            
        }
        
        public void añadirNuevosRegistros(List<Registro> nuevos){
            nuevosRegistros.addAll(nuevos);
            fireTableDataChanged();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirTransaccion;
    private javax.swing.JButton btnEliminarSeleccion;
    private javax.swing.JButton btnGuardarNuevasTransacciones;
    private javax.swing.JButton btnGuardarTransaccionModificada;
    private javax.swing.ButtonGroup btngTipoTransaccion;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtnAbono;
    private javax.swing.JRadioButton rbtnCargo;
    private javax.swing.JTable tablaRegistrosNuevos;
    private javax.swing.JTextField txtCuentaSeleccionada;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
